name: Bug report
description: Reporta un problema
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes: {label: Pasos para reproducir}
    validations: {required: true}
