name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps
        run: poetry install --no-interaction

      - name: Ruff lint
        run: poetry run ruff check . --fix

      - name: Ruff format
        run: poetry run ruff format .

      - name: Black check/format
        run: poetry run black .

      - name: Pytest + Coverage 100%
        env:
          PYTHONPATH: src
        run: poetry run pytest -q --cov=ai_patch_verifier --cov-report=term-missing --cov-fail-under=100

      - name: Header gate
        run: poetry run aipatch check-headers

      - name: Build wheel
        run: poetry build -q

      - name: Smoke install wheel
        run: |
          python -m venv .venv_smoke
          . .venv_smoke/bin/activate
          pip install -U pip
          pip install dist/*.whl
          aipatch --help > /dev/null
